### ISSUE TITLE
Wigle Request Failed BSSID/MAC fails validation

### ISSUE THREAD

**Issue by antmar904** [MarkBaggett/werejugo#3]
Hi Mark,

I am a current student taking SEC573 and I am trying to use your "werejugo" app.  I did create a Wigle API Name and Key and used it with your app but I am receiving the following error:

Bad things happened while talking to Wigle. OK, ('*************************', 'Wigle Request Failed BSSID/MAC fails validation.')  Continue? [Y/N]

**Comment by MarkBaggett** [comment]
Code updates.  Please give it a try.
